apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 
  - name: Loki
    type: loki
    access: proxy
  - name: Solr
    type: pue-solr-datasource
    access: proxy
    url: http://solr1:8983/solr/