version: '2.4'
services:
  zk1:
    build: zookeeper
    container_name: '${COMPOSE_PROJECT_NAME}_solr_zk1'
    environment:
      - SOLR_VERSION
      - NODE_EXPORTER_VERSION
      - JMX_EXPORTER_VERSION
      - PROMTAIL_VERSION
      - ZK_HOST=zk1
      - ZK_ID=1
    ports:
      - 9101:9100
      - 7071:7070
    volumes:
      - 'solr_zk1:/opt/zk'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  zk2:
    build: zookeeper
    container_name: '${COMPOSE_PROJECT_NAME}_solr_zk2'
    environment:
      - SOLR_VERSION
      - NODE_EXPORTER_VERSION
      - JMX_EXPORTER_VERSION
      - PROMTAIL_VERSION
      - ZK_HOST=zk2
      - ZK_ID=2
    volumes:
      - 'solr_zk2:/opt/zk'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  zk3:
    build: zookeeper
    container_name: '${COMPOSE_PROJECT_NAME}_solr_zk3'
    environment:
      - SOLR_VERSION
      - NODE_EXPORTER_VERSION
      - JMX_EXPORTER_VERSION
      - PROMTAIL_VERSION
      - ZK_HOST=zk3
      - ZK_ID=3
    volumes:
      - 'solr_zk3:/opt/zk'
    networks:
      - solr            
    restart: '${CONTAINER_RESTART}'

  solr1:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr_solr1'
    environment:
      - SOLR_VERSION
      - SOLR_HEAP
      - ZK_HOSTS
      - ZK_CHROOT
      - NODE_EXPORTER_VERSION
      - JMX_EXPORTER_VERSION
      - PROMTAIL_VERSION
      - SOLR_HOST=solr1
    ports:
      - 8983:8983
      - 9100:9100
      - 7070:7070
    volumes:
      - 'solr_solr1:/opt/solr'
      - 'solr_share:/opt/share'
      - './packages:/opt/packages'
      - '../volumes/${COMPOSE_PROJECT_NAME}/data:/opt/data'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  solr2:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr_solr2'
    environment:
      - SOLR_VERSION
      - SOLR_HEAP
      - ZK_HOSTS
      - ZK_CHROOT
      - NODE_EXPORTER_VERSION
      - JMX_EXPORTER_VERSION
      - PROMTAIL_VERSION
      - SOLR_HOST=solr2
    ports:
      - 8984:8983
    volumes:
      - 'solr_solr2:/opt/solr'
      - 'solr_share:/opt/share'
      - './packages:/opt/packages'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  solr3:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr_solr3'
    environment:
      - SOLR_VERSION
      - SOLR_HEAP
      - ZK_HOSTS
      - ZK_CHROOT
      - NODE_EXPORTER_VERSION
      - JMX_EXPORTER_VERSION
      - PROMTAIL_VERSION
      - SOLR_HOST=solr3
    ports:
      - 8985:8983
    volumes:
      - 'solr_solr3:/opt/solr'
      - 'solr_share:/opt/share'
      - './packages:/opt/packages'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  solr4:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr_solr4'
    environment:
      - SOLR_VERSION
      - SOLR_HEAP
      - ZK_HOSTS
      - ZK_CHROOT
      - NODE_EXPORTER_VERSION
      - JMX_EXPORTER_VERSION
      - PROMTAIL_VERSION
      - SOLR_HOST=solr4
    ports:
      - 8986:8983
    volumes:
      - 'solr_solr4:/opt/solr'
      - 'solr_share:/opt/share'
      - './packages:/opt/packages'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  client:
    build: client
    container_name: ${COMPOSE_PROJECT_NAME}_solr_client
    mem_limit: 1gb
    volumes:
      - './data/${COMPOSE_PROJECT_NAME}_solr:/opt/data'
    environment:
      - JAVA_OPTS=-XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=75.0 -XX:MaxMetaspaceSize=256M -Duser.timezone=Europe/Paris -Dhttps.protocols=TLSv1.1,TLSv1.2 -Xlog:gc*:file=/opt/searchws/log/gc.log::filecount=10,filesize=10m
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'


volumes:
  solr_zk1:
    driver: local
  solr_zk2:
    driver: local
  solr_zk3:
    driver: local
  solr_solr1:
    driver: local
  solr_solr2:
    driver: local
  solr_solr3:
    driver: local
  solr_solr4:
    driver: local
  solr_share:
    driver: local


networks:
  solr:
    name: '${COMPOSE_PROJECT_NAME}_solr'
    driver: bridge
