groups:
 
- name: Alertes monitoring
  rules:
    - alert: CpuLoad
      expr: node_load1{job="solr_node"} / (count without (cpu, mode) (node_cpu_seconds_total{job="solr_node",mode="idle"})) > 1
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "CPU load average per CPU (1mn)"
        description_starts: "Value is high : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"

    - alert: JvmHeapUsageSolr
      expr: max_over_time(java_lang_Memory_HeapMemoryUsage_used{instance=~"solr.*"}[1m]) / java_lang_Memory_HeapMemoryUsage_committed{instance=~"solr.*"} * 100 > 80
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Solr JVM Heap % usage average (1mn)"
        description_starts: "Value is high : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"

    - alert: JvmHeapUsageZk
      expr: max_over_time(java_lang_Memory_HeapMemoryUsage_used{instance=~"zk.*"}[1m]) / java_lang_Memory_HeapMemoryUsage_committed{instance=~"zk.*"} * 100 > 95
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Zk JVM Heap % usage average (1mn)"
        description_starts: "Value is high : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"

    - alert: JvmFullGcCount
      expr: increase(jvm_gc_collection_seconds_count{gc="ConcurrentMarkSweep"}[1m]) > 8
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Full JVM GC Count (1mn)"
        description_starts: "Value is high : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"

    - alert: JvmFullGcTime
      expr: increase(jvm_gc_collection_seconds_sum{gc="ConcurrentMarkSweep"}[1m]) / increase(jvm_gc_collection_seconds_count{gc="ConcurrentMarkSweep"}[1m]) > 1
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Full JVM GC Time (1mn)"
        description_starts: "Value is high : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"
  
    - alert: ZkCount
      expr: sum by (job) (zk_up) < 3
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Zookeeper up members count"
        description_starts: "Value is unexpected : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"
  
    - alert: ZkPendingSync
      expr: sum by (job) (zk_pending_syncs) > 2
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Zookeeper pending sync"
        description_starts: "Value is high : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"
  
    - alert: SolrDataFreeDisk
      expr: (node_filesystem_avail_bytes{job="solr_node",device=~".*sda[1-4]"}/node_filesystem_size_bytes{job="solr_node",device=~".*sda[1-4]"} * 100) < 20
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Solr data free disk"
        description_starts: "Value is low : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"


