groups:
 
- name: Alertes monitoring
  rules:
    - alert: CpuLoad
      expr: node_load1{job="solr_node"} / (count without (cpu, mode) (node_cpu_seconds_total{job="solr_node",mode="idle"})) > 1
      for: 1m
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "CPU load average (1mn)"
        description_starts: "Value is high : {{ $value }}"
        description_ends: "Value is back to normal : {{ $value }}"
