server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: solr
  static_configs:
  - targets:
      - localhost
    labels:
      host: ZK_HOST
      job: ZK_HOST
      __path__: /opt/zk/log/zookeeper.log
      