{
 "title": "Solr Minimal",
 "description": "Solr Minimal",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "solr1,solr2,solr3,solr4,zk1,zk2,zk3"
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware & System - CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load Average (1mn)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance.*\"}"
      }
     ]
    },
    {
     "title": "CPU Load Average per CPU (1mn)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance.*\"} / count without(cpu, mode) (node_cpu_seconds_total{instance=~\"$instance.*\",mode=\"idle\"})"
      }
     ]
    },
    {
     "title": "CPU Usage % (1 mn)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$instance.*\",mode=\"idle\"}[1m])) * 100)"
      }
     ]
    },
    {
     "title": "CPU IOWait  % (1 mn)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$instance.*\",mode=\"iowait\"}[1m])) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware & System - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance.*\"} - node_memory_SwapFree_bytes{instance=~\"$instance.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware & System - Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O global % (1mn)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$instance.*\",device=\"sda\"}[1m])"
      }
     ]
    },
    {
     "title": "Disk I/O Read Count (1mn)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance.*\",device=\"sda\"}[1m])"
      }
     ]
    },
    {
     "title": "Disk I/O write count (1mn)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance.*\",device=\"sda\"}[1m])"
      }
     ]
    },
    {
     "title": "Disk Free Space (%)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_avail_bytes{instance=~\"$instance.*\",device=\"/dev/sda1\"}/node_filesystem_size_bytes{instance=~\"$instance.*\",device=\"/dev/sda1\"} * 100)"
      }
     ]
    },
    {
     "title": "Disk Free Space (GB)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$instance.*\",device=\"/dev/sda1\"} "
      }
     ]
    }
   ]
  },
  { "title": "JVM - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "GC Time / mn",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"$instance.*\"}[1m])"
    }
   ]
  },
  {
   "title": "GC Count / mn",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{instance=~\"$instance.*\"}[1m])"
    }
   ]
  },
  {
   "title": "CG Time / GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"$instance.*\"}[1m]) / increase(jvm_gc_collection_seconds_count{instance=~\"$instance.*\"}[1m])"
    }
   ]
  },
  { "title": "JVM - Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$instance.*\"} [1m])"
    }
   ]
  },
  {
   "title": "Heap Used (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$instance.*\"} [1m]) / java_lang_Memory_HeapMemoryUsage_committed{instance=~\"$instance.*\"} * 100"
    }
   ]
  }
 ]
}