{
 "title": "Zookeeper Minimal",
 "description": "Dashboard for https://github.com/dabealu/zookeeper-exporter\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "zk1,zk2,zk3" }
  ]
 },
 "panels": [
  { "title": "ZK1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Zk1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "zk_up{zk_host=~\"zk1.*\"}"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "zk_server_leader{zk_host=~\"zk1.*\"}"
    }
   ]
  },
  {
   "title": "ZK2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Status Zk2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "zk_up{zk_host=~\"zk2.*\"}"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "zk_server_leader{zk_host=~\"zk2.*\"}"
    }
   ]
  },
  {
   "title": "ZK3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Status Zk3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "zk_up{zk_host=~\"zk3.*\"}"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "zk_server_leader{zk_host=~\"zk3.*\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Max Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_max_latency{zk_host=~\"$instance.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{zk_host=~\"$instance.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{zk_host=~\"$instance.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pending sync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_pending_syncs{zk_host=~\"$instance.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pakages Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zk_packets_sent{zk_host=~\"$instance.*\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pakages Recieved",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zk_packets_received{zk_host=~\"$instance.*\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_num_alive_connections{zk_host=~\"$instance.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{zk_host=~\"$instance.*\"}",
     "legendFormat": "open"
    },
    {
     "expr": "zk_max_file_descriptor_count{zk_host=~\"$instance.*\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "ZNode count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_znode_count{zk_host=~\"$instance.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}